using APPCOVID.DAL.DataManagers.Core;
using APPCOVID.DAL.DataManagers.Helper;
using APPCOVID.Entity.DTO;
using System.Collections.Generic;

namespace APPCOVID.DAL.DataManagers.Managers
{
    public class ProductManager : DataManager<ProductDto>
    {
        #region Db Queries 
        private readonly string createTableQuery = $@"CREATE TABLE {DalCostants.TABLE_SCHEMA}.{DalCostants.PRODUCT_TABLE}" +
           "( PRODUCTID INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, " +
           "PRODUCTTYPE VARCHAR(50) NOT NULL, " +
           "CUSTOMERID INT NOT NULL, " +
           "STAGE INT NOT NULL, " +
           "DESCRIPTION VARCHAR(500) NULL, " +
           "SHORTDESCRIPTION VARCHAR(100) NOT NULL, " +
           "IMAGEURL VARCHAR(500) NULL, " +
           "PRODUCTURL VARCHAR(500) NULL, " +
           "STATUS VARCHAR(20) NOT NULL, " +
           "PRIMARY KEY (PRODUCTID) );";

        private readonly string getAllDataQuery = $@"select * from {DalCostants.TABLE_SCHEMA}.{DalCostants.PRODUCT_TABLE}";


        #endregion

        private DataManager<ProductDto> _dataManager;

        public ProductManager()
        {
            _dataManager = new DataManager<ProductDto>();
            if (!_dataManager.IsTableExistsinDb(DalCostants.TABLE_SCHEMA, DalCostants.PRODUCT_TABLE))
            {
                _dataManager.CreateNewTable(createTableQuery, DalCostants.TABLE_SCHEMA, DalCostants.PRODUCT_TABLE);
            }
        }

        public List<ProductDto> GetProductData()
        {
            return _dataManager.GetData(getAllDataQuery);
        }

        public bool CreateInsuranceProduct(ProductDto product)
        {
            string prepareQuery = $@"insert into {DalCostants.TABLE_SCHEMA}.{DalCostants.PRODUCT_TABLE} (PRODUCTTYPE,CUSTOMERID,STAGE,DESCRIPTION,SHORTDESCRIPTION,IMAGEURL,PRODUCTURL,STATUS)
                            values('{product.PRODUCTTYPE}', {product.CUSTOMERID}, {product.STAGE}, '{product.DESCRIPTION}','{product.SHORTDESCRIPTION}', '{product.IMAGEURL}','{product.PRODUCTURL}', '{product.STATUS}')";
            return _dataManager.InsertData(prepareQuery);
        }
        public bool UpdateInsuranceProduct(ProductDto product)
        {
            string prepareQuery = $@"update {DalCostants.TABLE_SCHEMA}.{DalCostants.PRODUCT_TABLE}
                                    set DESCRIPTION='{product.DESCRIPTION}',
                                        SHORTDESCRIPTION='{product.SHORTDESCRIPTION}',
                                        IMAGEURL='{product.IMAGEURL}',
                                        PRODUCTURL='{product.PRODUCTURL}',
                                        STATUS='{product.STATUS}',
                                        CUSTOMERID='{product.CUSTOMERID}',
                                        STAGE='{product.STAGE}'
                                   where PRODUCTID=" +product.PRODUCTID+"";
            return _dataManager.InsertData(prepareQuery);
        }

    }
}
