using APPCOVID.DAL.DataManagers.Core;
using APPCOVID.DAL.DataManagers.Helper;
using APPCOVID.Entity.DTO;
using System.Collections.Generic;

namespace APPCOVID.DAL.DataManagers.Managers
{
    public class TransactionManager : DataManager<TransactionDto>
    {
        #region Db Queries 
        private readonly string createTableQuery = $@"CREATE TABLE {DalCostants.TABLE_SCHEMA}.{DalCostants.TRANSACTION_TABLE}" +
           "( TRANSACTIONID INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, " +
           "PRODUCTID INT NOT NULL, " +
           "CUSTOMERID INT NOT NULL, " +
           "SUBSCRIPTIONTYPE VARCHAR(20) NOT NULL, " +
           "PODETAILS VARCHAR(500) NOT NULL, " +
           "CREATEDDATE VARCHAR(30) NOT NULL, " +
           "VALIDUPTODATE VARCHAR(30) NOT NULL, " +
           "STATUS VARCHAR(20) NOT NULL, " +
           "PRIMARY KEY (TRANSACTIONID) );";

        private readonly string getAllDataQuery = $@"select * from {DalCostants.TABLE_SCHEMA}.{DalCostants.TRANSACTION_TABLE}";


        #endregion

        private DataManager<TransactionDto> _dataManager;

        public TransactionManager()
        {
            _dataManager = new DataManager<TransactionDto>();
            if (!_dataManager.IsTableExistsinDb(DalCostants.TABLE_SCHEMA, DalCostants.TRANSACTION_TABLE))
            {
                _dataManager.CreateNewTable(createTableQuery, DalCostants.TABLE_SCHEMA, DalCostants.TRANSACTION_TABLE);
            }
        }

        public List<TransactionDto> GetTransactionData()
        {
            return _dataManager.GetData(getAllDataQuery);
        }

        public bool CreateTransactionData(TransactionDto transaction)
        {
            string prepareQuery = $@"insert into {DalCostants.TABLE_SCHEMA}.{DalCostants.TRANSACTION_TABLE} (PRODUCTID,CUSTOMERID,SUBSCRIPTIONTYPE,PODETAILS,CREATEDDATE,VALIDUPTODATE,STATUS)
                            values({transaction.PRODUCTID}, {transaction.CUSTOMERID}, '{transaction.SUBSCRIPTIONTYPE}', '{transaction.PODETAILS}','{transaction.CREATEDDATE}', '{transaction.VALIDUPTODATE}','{transaction.STATUS}')";
            return _dataManager.InsertData(prepareQuery);
        }
        public bool UpdateProductTransaction(TransactionDto transaction)
        {
            string prepareQuery = $@"update {DalCostants.TABLE_SCHEMA}.{DalCostants.TRANSACTION_TABLE}
                                    set SUBSCRIPTIONTYPE='{transaction.SUBSCRIPTIONTYPE}',
                                        VALIDUPTODATE='{transaction.VALIDUPTODATE}',                             
                                        STATUS='{transaction.STATUS}'
                                   where TRANSACTIONID=" + transaction.TRANSACTIONID + "";
            return _dataManager.InsertData(prepareQuery);
        }
    }
}
